---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: candycrush
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candycrush
  template:
    metadata:
      labels:
        app: candycrush
    spec:
      containers:
      - name: candycrush
        image: sevensaurav/candycrush:latest
        ports:
        - containerPort: 8000   # Use port 8000

---
apiVersion: v1
kind: Service
metadata:
  name: candycrush-service
spec:
  selector:
    app: candycrush
  ports:
  - protocol: TCP
    port: 90                 # Expose port 90
    targetPort: 8000
  type: LoadBalancer
